blue-badge:
  auth-server: 
    url: https://authorisation-service.${bb_env}.${url}/bb_auth
  reference-data-service:
    service-host:
      host: reference-service.${bb_env}.${url}
      port: 443
      scheme: https
  message-service:
    service-host:
      host: messaging-service.${bb_env}.${url}
      port: 443
      scheme: https

management:
  server:
    port: ${bb_health:-8081}

spring:
  main:
    banner-mode: "off"
  datasource:
     ***REMOVED***
    username: ${bb_db_username:-developer}
    url: jdbc:postgresql://${RDS_HOSTNAME}:5432/${bb_database:-bb_dev}?currentSchema=applicationmanagement&sslmode=verify-full

server:
  port: ${bb_port:-8080}

amazon:
  s3bucket: ${bb_application_artifact_bucket}
