blue-badge: 
  auth-server:
    url: https://authorisation-service.${bb_env}.${url}/bb_auth
  usermanagementservice:
    servicehost:
      host: usermanagement-service.${bb_env}.${url}
      port: 443
      scheme: https
  badgemanagementservice:
    servicehost:
      host: badge-service.${bb_env}.${url}
      port: 443
      scheme: https
  referencedataservice:
    servicehost:
      host: reference-service.${bb_env}.${url}
      port: 443
      scheme: https
  applicationsservice:
    servicehost:
      host: application-service.${bb_env}.${url}
      port: 443
      scheme: https

management:
  server:
    port: ${bb_health:-8081}

spring:
  datasource:
     ***REMOVED***
    username: ${bb_db_username:-developer}
    url: jdbc:postgresql://postgres-service.${bb_env}.${url}:5432/${bb_database:-bb_dev}?currentSchema=applicationmanagement

server:
  port: ${bb_port:-8080}
